"use client"

import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import { PageBanner } from "@/components/page-banner"
import { Card, CardContent } from "@/components/ui/card"
import { AlertTriangle, Lightbulb, Target, Eye, Zap, Users, Leaf, Heart } from "lucide-react"
import { motion } from "framer-motion"

export default function AboutPage() {
  return (
    <div className="min-h-screen bg-white">
      <style jsx global>{`
        @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800&display=swap');
        .montserrat { font-family: 'Montserrat', sans-serif; }
        .montserrat-bold { font-family: 'Montserrat', sans-serif; font-weight: 800; }
      `}</style>
      
      <Header />
      
      {/* IMPROVED BANNER - Maximized Visibility for firepic.jpg */}
      <section className="relative h-[60vh] lg:h-[70vh] flex items-center justify-center overflow-hidden">
  {/* Background Image */}
  <div 
    className="absolute inset-0 bg-cover bg-center transition-transform duration-[7000ms] ease-out hover:scale-110"
    style={{ backgroundImage: "url('/aboutbanner.png')" }}
  />
  
  {/* Lightened overlay so the brand colors aren't muddied */}
  <div className="absolute inset-0 bg-white/10" />

  {/* Content Area - Minimalist Style */}
  <div className="relative z-10 w-full px-6 text-center">
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 1 }}
      className="max-w-4xl mx-auto"
    >
      
    </motion.div>
  </div>
</section>

      <main className="montserrat">
        
        {/* SECTION 1: THE PROBLEM & SOLUTION */}
        <section className="py-24 bg-white">
          <div className="max-w-7xl mx-auto px-6 lg:px-12">
            <div className="grid lg:grid-cols-2 gap-0 shadow-2xl border border-gray-100">
              
              {/* THE PROBLEM */}
              <div className="bg-[#001a3d] p-10 lg:p-20 text-white flex flex-col justify-center">
                <div className="flex items-center space-x-4 mb-8">
                  
                  <h2 className="montserrat-bold text-2xl tracking-[0.3em] uppercase">The Problem</h2>
                </div>
                <div className="space-y-6 text-gray-300 font-medium leading-relaxed text-lg">
                  <p>
                    More than 900 Million People in Africa have no access to clean cooking energy, and this cause more than 800,000 premature deaths annually. <span className="text-white font-bold">With a continuous growing </span> of Populations, cooking energy demand also increases,
                  while 57% of wastes generated by that population are organic wastes that are outpacing the capacity of municipal wastes dumping sites.
                  </p>
                </div>
              </div>

              {/* THE SOLUTION */}
              <div className="bg-white p-10 lg:p-20 flex flex-col justify-center border-l border-gray-100">
                <div className="flex items-center space-x-4 mb-8">
                  
                  <h2 className="montserrat-bold text-2xl tracking-[0.3em] uppercase text-[#002868]">Solution</h2>
                </div>
                <div className="space-y-6 text-gray-600 font-medium leading-relaxed text-lg">
                  <p>
                    Green Fuel is Rwandan based social company  <span className="text-green-700 font-bold italic">that Provide affordable clean cooking gas</span> made from local organic waste <strong>"Where we provide on sites biodigesters installation"</strong> and monitoring services for farmers and institutions
                  </p>
                  <p>
                    and cylinder stored biogas for people with inadequate daily waste generation or space to run a biodigester. 
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* SECTION 2: COMPARISON - Full Image Visibility */}
        <section className="pb-24 bg-white">
          <div className="max-w-7xl mx-auto px-6 lg:px-12">
             <div className="text-center mb-12">
                <h3 className="montserrat-bold text-3xl text-[#002868] uppercase tracking-tighter">Energy Transformation</h3>
             </div>
            <div className="grid md:grid-cols-2 gap-8">
              <div className="relative group">
                <div className="aspect-video w-full overflow-hidden border border-gray-200">
                  <img src="/beforegreenergy.jpg" className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105" alt="Before" />
                </div>
                <div className="mt-4">
                  <p className="montserrat-bold text-[#002868] text-lg uppercase tracking-widest">Before Green Fuel gas</p>
                  <p className="text-gray-500 font-bold italic text-sm mt-1 uppercase">EXPENSIVE COOKING FUELS, CHOCKING SMOKE, DIRTNESS IN THE KITCHEN, RESIPIRATORY DISEASES.</p>
                </div>
              </div>

              <div className="relative group">
                <div className="aspect-video w-full overflow-hidden border border-gray-200">
                  <img src="/bg5.jpg" className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105" alt="After" />
                </div>
                <div className="mt-4">
                  <p className="montserrat-bold text-green-700 text-lg uppercase tracking-widest">With Green Fuel gas</p>
                  <p className="text-gray-500 font-bold italic text-sm mt-1 uppercase">RELIEVED PEOPLE, CLEAN AND HEALTH COOKING ENVIRONMENT AND COOKING FUEL COST SAVING.</p>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* SECTION 3: CORE VALUES */}
        <section className="py-24 bg-gray-50">
          <div className="max-w-7xl mx-auto px-6 lg:px-12 text-center">
            <h3 className="montserrat-bold text-4xl lg:text-5xl text-[#002868] mb-16 uppercase">Core Values</h3>
            <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
              {[
                { icon: Zap, title: "Innovation", desc: "We leverage digital monitoring and circular economy principles to turn environmental challenges into economic opportunities." },
                { icon: Users, title: "Accountability", desc: "We take full ownership of the organic waste and energy crisis, delivering measurable results for the planet and our people." },
                { icon: Leaf, title: "Inclusion", desc: "We design for the underserved, ensuring women and rural families have equitable access to clean, affordable technology." },
                { icon: Heart, title: "Integrity", desc: "We provide transparent, reliable energy solutions that prioritize health, safety, and long-term community trust." }
              ].map((val, i) => (
                <div key={i} className="bg-white p-10 shadow-lg border-b-4 border-green-600 group">
                  <val.icon className="h-10 w-10 mb-6 mx-auto text-green-700" />
                  <h4 className="montserrat-bold text-lg text-[#002868] mb-4 uppercase tracking-widest">{val.title}</h4>
                  <p className="text-gray-500 text-xs font-bold leading-relaxed uppercase">{val.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* SECTION 4: MISSION & VISION */}
        <section className="bg-[#001a3d] text-white py-24 px-6 lg:px-12">
          <div className="max-w-7xl mx-auto grid md:grid-cols-2 gap-16">
            <div className="space-y-6">
              <Target className="h-14 w-14 text-green-500" />
              <h3 className="montserrat-bold text-3xl tracking-widest uppercase">Our Mission</h3>
              <p className="text-xl font-medium text-gray-300 leading-relaxed">
                We are on the mission to transform lives through affordable clean cooking energy made from local organic wastes.
              </p>
            </div>
            <div className="space-y-6">
              <Eye className="h-14 w-14 text-green-500" />
              <h3 className="montserrat-bold text-3xl tracking-widest uppercase">Our Vision</h3>
              <p className="text-xl font-medium text-gray-300 leading-relaxed">
                We envision being a leading cooking energy trusted partner for African households and institution. 
              </p>
            </div>
          </div>
        </section>

        {/* SECTION 5: OUR STORY */}
        <section className="py-24 bg-white">
          <div className="max-w-5xl mx-auto px-6 lg:px-12">
            <div className="text-center mb-16">
              <h2 className="montserrat-bold text-4xl lg:text-6xl text-[#002868] uppercase tracking-tighter">Our Story</h2>
              <div className="h-2 w-20 bg-green-500 mx-auto mt-6" />
            </div>

            <div className="prose prose-xl max-w-none montserrat font-medium text-gray-700 space-y-12 leading-relaxed">
              <p className="text-2xl lg:text-3xl montserrat-bold text-[#002868] border-l-8 border-green-600 pl-8">
                "Green Fuel Ltd was born in the heart of Rwamagana District, Eastern Province of Rwanda in 2024, from a glaring contradiction: while families were struggling with the rising costs of LPG gas and respiratory tolls of wood based fuels, their farms, nearby markets, household’s wastes bins were overflowing with untapped organic waste. "
              </p>
              
              <div className="space-y-8">
                <p>
                 Witnessing women trek miles for firewood only to cook in toxic smoke while municipal dumpsites reached breaking point sparked our mission. Through continuous research, and development, we realized that waste wasn't a burden; it was a buried energy source. By bridging the gap between waste management and affordable cooking energy through digitally monitored biodigesters, and cylinder stored biogas, we have turned an energy crisis and waste management into a circular economy that empowers families.
                 </p>
                
                <div className="bg-[#001a3d] p-12 text-white shadow-2xl border-l-8 border-green-500">
                  <p className="text-xl lg:text-2xl font-bold italic uppercase tracking-tight">
                    "TO date, through our solutions , we have been able to impact families in Eastern province of Rwanda with affordable, clean cooking energy, and this has proven to save them 60% of their usual cooking energy costs, has reduced respiratory related diseases, because of displacing wood based fuels, the inhalation of toxic smokes from burning wood fuels stopped, with the reduction of wood fuels dependency, this has also reduced deforestation. Increased 40% of farms productivity because of a nutritious organic fertilizer provided to farmers which is yielded from the gas Production processes, has also created  jobs and abate thousands tons of CO2 emissions"
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  )
}